config/routes.rb
Rails.application.routes.draw do

  #Destroy
  delete '/logout', to: "sessions#destroy", as: 'logout'

  #Login  
  post '/login', to: "sessions#create", as: "new_user_session"
  get '/login', to: "sessions#login", as: "login"

  #Sign UP
  post '/signup', to: "users#create", as: "new_user_registration"
  get '/signup', to: "users#new", as: "signup"

  #Articles
  delete "/article/:id", to: "articles#destroy", as: "article_destroy"
  patch "/article/:id", to: "articles#update"
  get "/article/:id/edit", to: "articles#edit", as: "article_edit"
  get "/article/:id", to: "articles#show", as: "article"
  post "/articles", to: "articles#create"
  get "/articles", to: "articles#index" 
  get "/articles/new", to: "articles#new" 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
    validates :email, presence: true
    validates :password, length: {minimum: 6}
    validates :password_confirmation, length: {minimum: 6}
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  helper_method :current_user

  def current_user
      User.find(session[:user_id]) if session[:user_id]
  end

  private

  def authenticate_user!
      redirect_to login_path, notice: "You have to be logged in." unless current_user
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: %i[show edit update destroy]

 def index
    @articles = Article.all
 end

 def new
    @article = Article.new
 end

 def show
 end

 def edit
 end

 def create
    @article = Article.new(article_params)

    if @article.save
        redirect_to articles_path, notice: "Article was created."
    else
        render :new, status: :unprocessable_entity
    end
 end

 def update
    if @article.update(article_params)
        redirect_to articles_path(@article)
    else
        render :edit, status: :unprocessable_entity
    end
 end

 def destroy
    @article.destroy
    redirect_to articles_path
 end

 private

 def article_params
    params.require(:article).permit(:name, :description)
 end

 def set_article
    @article = Article.find(params[:id])
 end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @num = 11    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    skip_before_action :authenticate_user!, only: %i[login create]


    def login
    end

    def create
       #debugger 

       @user = User.find_by(email: params[:session][:email])

       if @user.present? && @user.authenticate(params[:session][:password])
        session[:user_id] = @user.id
        redirect_to root_path, notice: "Login succesfully"
       else
        redirect_to login_path, notice: "Email or password incorrect"
       end
    end

    def destroy
        session[:user_id] = nil
        redirect_to login_path, notice: "Logout succesfully"
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user!, only: %i[new create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: "Sign up succesfully"
    else
      render :new, status: :unprocessable_entity
    end  
  end

  private
  
  def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
  end

    
    
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<div>
    <%= form_with(model: @article) do |form| %>
      <% if @article.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

          <ul>
            <% @article.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :name, 'Insert name: ' %>
        <%= form.text_field :name %>
      </div>
      <br>    
      <div>
        <%= form.label :description, 'Insert description: ' %>
        <%= form.text_field :description %>
      </div>  
      <div>
          <%= form.submit %>
      </div>  
    <% end %>          
</div>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Articles<h1>

<% @articles.each do |article| %>
    <div>
        <strong> <%= article.name %> </strong> <br>
        <%= article.description %>
        <%= link_to 'See more', article_path(article) %>
    </div>
<% end %>
  

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1>Show Article</h1>

<div>
    <h3> <%= @article.name %>  </h3>
    <div>
        <%= @article.description %> 
    </div>

    <div>
        <%= link_to 'Edit article', article_edit_path(@article) %>
        <%= button_to 'Delete article', article_destroy_path(@article), method: :delete %>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= notice if notice%>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1> Hello World!<h1>
<%= @num %>

<% if @num > 100 %>
    <p>El número es mayor a 100</>
<% else %>
    <p> El número no es mayor a 100</p>
<% end %>

app/views/shared/_header.html.erb
<nav>
    <ul>
      <li> <%= link_to 'Rails App' , root_path  %> </li>
      <li> <%= link_to 'Articles' , articles_path  %> </li>
      <li> <%= link_to 'New article' , articles_new_path  %> </li>
      <% if current_user %>
        <li> <%= button_to 'log out', logout_path, method: :delete %> </li>
        <li> 
          <%= current_user.email %> 
        </li>
      <% else %>  
        <li> <%= link_to 'Login', login_path  %> </li>
        <li> <%= link_to 'Sign up', signup_path  %> </li>
      <% end %>
    </ul>
</nav>

app/views/users/new.html.erb
<h1>Sign up </h1>

<div>
    <%= form_with(model: @user, url: new_user_registration_path) do |form| %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

          <ul>
            <% @user.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :email %>
        <%= form.email_field :email %>
      </div>

      <div>
        <%= form.label :password %>
        <%= form.password_field :password %>
      </div>

      <div>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation %>
      </div>

      <div>
        <%= form.submit 'Sign up' %>
      </div>

    <% end %>
</div>